import { useEffect, useMemo, useRef, useState } from 'react';

type Member={id:string;name:string;role:string;birthDate:string;birthTime:string;gender:string;note?:string};
type Pillars={year:string;month:string;day:string;time:string;elements:Record<string,number>};
const KEY='family-saju-members-v6';
const roles=['본인','배우자','아빠','엄마','아들','딸','할아버지','할머니','형제','자매','기타'];
const stems=['갑','을','병','정','무','기','경','신','임','계'],branches=['자','축','인','묘','진','사','오','미','신','유','술','해'];
const el=(c:string)=>({갑:'목',을:'목',인:'목',묘:'목',병:'화',정:'화',사:'화',오:'화',무:'토',기:'토',진:'토',축:'토',술:'토',미:'토',경:'금',신:'금',유:'금',임:'수',계:'수',자:'수',해:'수'} as Record<string,string>)[c]||'토';
const avatar=(r:string)=>['엄마','할머니','딸','자매'].includes(r)?'👩':['아빠','할아버지','아들','형제','배우자'].includes(r)?'👨':r==='본인'?'🧑':'👤';
const pad=(n:number)=>String(n).padStart(2,'0');
const formatToday=()=>{const d=new Date();return `${d.getFullYear()}.${pad(d.getMonth()+1)}.${pad(d.getDate())}`};
function calc(date:string,time:string):Pillars{const [ys,ms,ds]=date.split('-').map(Number);const [hh,mm]=String(time||'12:00').split(':').map(Number);const valid=Number.isFinite(ys)&&Number.isFinite(ms)&&Number.isFinite(ds)&&ys>1800&&ms>=1&&ms<=12&&ds>=1&&ds<=31;const y=valid?ys:2000,m=valid?ms:1,day=valid?ds:1,h=Number.isFinite(hh)?Math.max(0,Math.min(23,hh)):12;const py=m>2||(m===2&&day>=4)?y:y-1,yi=((py-4)%60+60)%60;const year=stems[yi%10]+branches[yi%12];const td=[6,4,6,5,6,6,7,7,8,8,7,7],mb=[1,2,3,4,5,6,7,8,9,10,11,0];let bm=mb[m-1]-(day<td[m-1]?1:0);bm=(bm+12)%12;const ms=((yi%10)%5*2+bm)%10,month=stems[ms]+branches[bm];const days=Math.floor(Date.UTC(y,m-1,day)/86400000),di=((days+49)%60+60)%60,dayP=stems[di%10]+branches[di%12],hb=Math.floor(((h+1)%24)/2),timeP=stems[(di%10*2+hb)%10]+branches[hb];const elements={목:0,화:0,토:0,금:0,수:0} as Record<string,number>;[year,month,dayP,timeP].forEach(p=>[...p].forEach(c=>elements[el(c)]++));return{year,month,day:dayP,time:timeP,elements}}
function relation(a:Pillars,b:Pillars){const x=a.elements,y=b.elements;const totalA=Object.values(x).reduce((s,v)=>s+v,0)||1,totalB=Object.values(y).reduce((s,v)=>s+v,0)||1;const similarity=Object.keys(x).reduce((s,k)=>s+Math.min(x[k]/totalA,y[k]/totalB),0)/5;const generating=(x.목*y.화+x.화*y.토+x.토*y.금+x.금*y.수+x.수*y.목)/(totalA*totalB);const balanceA=1-Math.max(...Object.values(x))/totalA,balanceB=1-Math.max(...Object.values(y))/totalB;const raw=50+similarity*28+Math.min(1,generating*2)*12+(balanceA+balanceB)*5;const score=Math.max(45,Math.min(96,Math.round(raw)));return score>=80?{score,label:'아주 좋은 조화',tone:'good',text:'서로의 강점을 살려주기 쉬운 흐름입니다.'}:score>=65?{score,label:'좋은 관계 흐름',tone:'mid',text:'차이를 인정하면 안정적인 협력이 가능한 조합입니다.'}:{score,label:'대화가 중요한 관계',tone:'care',text:'속도와 표현 방식의 차이를 먼저 이해하면 관계가 편해집니다.'}}
const todayText=['오늘은 결론을 서두르기보다 상대의 말을 한 번 더 확인하기 좋은 날입니다.','작은 약속 하나를 지키는 것이 가족 사이의 신뢰를 크게 높여줍니다.','감정적인 평가보다 구체적인 사실과 원하는 행동을 이야기해 보세요.'];
function App(){
 const[members,setMembers]=useState<Member[]>([]),[selectedId,setSelectedId]=useState(''),[meId,setMeId]=useState(''),[view,setView]=useState<'home'|'family'|'relationship'>('home'),[showForm,setShowForm]=useState(false),[editId,setEditId]=useState(''),[query,setQuery]=useState(''),[compareId,setCompareId]=useState(''),[situation,setSituation]=useState(''),[loaded,setLoaded]=useState(false);const fileRef=useRef<HTMLInputElement>(null);
 const blank={name:'',role:'본인',birthDate:'',birthTime:'12:00',gender:'남성',note:''};const[form,setForm]=useState<Member>(blank);
 useEffect(()=>{try{const raw=localStorage.getItem(KEY);if(raw){const d=JSON.parse(raw);if(Array.isArray(d.members))setMembers(d.members);if(typeof d.meId==='string')setMeId(d.meId)}}catch{}setLoaded(true)},[]);
 useEffect(()=>{if(loaded)localStorage.setItem(KEY,JSON.stringify({version:6,members,meId}))},[loaded,members,meId]);
 const selected=members.find(m=>m.id===selectedId)||members[0], me=members.find(m=>m.id===meId), compare=members.find(m=>m.id===compareId), selectedP=selected?calc(selected.birthDate,selected.birthTime):null;
 const filtered=members.filter(m=>`${m.name} ${m.role}`.toLowerCase().includes(query.toLowerCase()));
 const ranking=useMemo(()=>{if(!selected)return[];return members.filter(m=>m.id!==selected.id).map(m=>({m,r:relation(calc(selected.birthDate,selected.birthTime),calc(m.birthDate,m.birthTime))})).sort((a,b)=>b.r.score-a.r.score)},[members,selected]);
 const guide=situation==='진로'?'조언부터 하기보다 “어떤 선택지가 가장 끌려?”라고 물어보세요.':situation==='돈'?'숫자와 사실을 먼저 맞춘 뒤 감정에 대한 평가는 나중에 이야기해 보세요.':situation==='부부갈등'?'누가 맞는지보다 “지금 내가 바라는 변화 한 가지”를 말하는 것이 좋습니다.':situation==='자녀'?'결과보다 과정과 노력을 먼저 인정하고 다음 행동을 함께 정해보세요.':situation==='부모님'?'걱정에서 나온 말이라는 점을 인정한 뒤 내가 원하는 도움의 범위를 구체적으로 알려주세요.':'상대의 말을 먼저 한 문장으로 요약한 뒤 내 생각과 원하는 행동을 말해보세요.';
 function openAdd(){setEditId('');setForm({...blank,role:members.some(m=>m.role==='본인')?'아빠':'본인'});setShowForm(true)}
 function openEdit(m:Member){setEditId(m.id);setForm({...m});setShowForm(true)}
 function save(e:React.FormEvent){e.preventDefault();if(!form.name.trim()||!form.birthDate||!form.birthTime)return;if(editId){setMembers(p=>p.map(m=>m.id===editId?{...form,id:editId,name:form.name.trim()}:m));setSelectedId(editId)}else{const n={...form,id:crypto.randomUUID(),name:form.name.trim()};setMembers(p=>[...p,n]);setSelectedId(n.id);if(!meId&&n.role==='본인')setMeId(n.id)}setShowForm(false)}
 function remove(id:string){if(!confirm('이 가족 구성원을 삭제할까요?'))return;setMembers(p=>p.filter(m=>m.id!==id));if(meId===id)setMeId('');if(compareId===id)setCompareId('');if(selectedId===id)setSelectedId('')}
 function backup(){const blob=new Blob([JSON.stringify({version:6,exportedAt:new Date().toISOString(),members,meId},null,2)],{type:'application/json'}),u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download='family-saju-backup.json';a.click();URL.revokeObjectURL(u)}
 function restore(e:React.ChangeEvent<HTMLInputElement>){const f=e.target.files?.[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const d=JSON.parse(String(r.result));if(!Array.isArray(d.members))throw 0;const clean=d.members.filter((m:Member)=>m&&typeof m.name==='string'&&typeof m.birthDate==='string'&&typeof m.birthTime==='string').map(m=>({...m,id:typeof m.id==='string'?m.id:crypto.randomUUID()}));setMembers(clean);setMeId(typeof d.meId==='string'&&clean.some(m=>m.id===d.meId)?d.meId:'');setSelectedId(clean[0]?.id||'');alert(`${clean.length}명의 가족 정보를 복원했습니다.`)}catch{alert('올바른 Family Saju AI 백업 파일이 아닙니다.')}finally{e.target.value=''}};r.readAsText(f)}
 const go=(v:'home'|'family'|'relationship')=>setView(v);
 return <div className="app"><header className="topbar"><button className="brand" onClick={()=>go('home')}><span className="brand-mark">☯</span><span><strong>Family Saju AI</strong><small>가족을 이해하는 새로운 방법</small></span></button><nav><button className={view==='home'?'on':''} onClick={()=>go('home')}>홈</button><button className={view==='family'?'on':''} onClick={()=>go('family')}>가족</button><button className={view==='relationship'?'on':''} onClick={()=>go('relationship')}>관계 분석</button></nav><div className="top-actions"><button onClick={backup} disabled={!members.length}>백업</button><button onClick={()=>fileRef.current?.click()}>복원</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={restore}/></div></header>
 <div className="layout"><aside className="sidebar"><div className="side-head"><div><p className="eyebrow">MY FAMILY</p><b>우리 가족</b></div><button className="icon-btn" onClick={openAdd}>＋</button></div><div className="side-search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="가족 찾기"/></div><div className="side-list">{filtered.map(m=><button className={`side-member ${selected?.id===m.id?'selected':''}`} key={m.id} onClick={()=>{setSelectedId(m.id);go('family')}}><span className="side-avatar">{avatar(m.role)}</span><span><b>{m.name}</b><small>{m.role}{m.id===meId?' · 나':''}</small></span></button>)}{!members.length&&<div className="side-empty">등록된 가족이 없습니다.</div>}</div><button className="side-add" onClick={openAdd}>＋ 가족 구성원 추가</button><div className="privacy-mini">🔒 입력 정보는 이 브라우저에만 저장됩니다.</div></aside>
 <main className="content">{view==='home'&&<><section className="hero"><div><p className="eyebrow">FAMILY RELATIONSHIP</p><h1>사주를 보고,<br/><em>대화의 방법</em>을 찾습니다.</h1><p className="hero-copy">가족의 생년월일시를 바탕으로 사주의 흐름을 정리하고, 가족 사이의 차이를 대화의 언어로 풀어봅니다.</p><div className="hero-actions"><button className="primary" onClick={()=>members.length?go('family'):openAdd()}>{members.length?'가족 보기':'첫 가족 등록하기'} <span>→</span></button>{members.length>1&&<button className="secondary" onClick={()=>go('relationship')}>관계 분석 시작</button>}</div></div><div className="hero-card"><span>FAMILY BOARD</span><strong>{members.length?`${members.length}명의 가족이 함께하고 있어요`:'가족 보드를 만들어 보세요'}</strong><p>{members.length?'가족을 선택하면 개인 사주와 관계 분석을 바로 확인할 수 있습니다.':'가족의 생년월일시를 등록하면 이 브라우저에서 계속 사용할 수 있습니다.'}</p><div className="hero-stat"><b>{members.length}</b><span>PROFILES</span></div></div></section><section className="section"><div className="section-head"><div><p className="eyebrow">TODAY</p><h2>오늘의 가족 가이드</h2></div><span className="date-chip">{formatToday()}</span></div><div className="today"><div className="today-mark">☯</div><div><b>{todayText[members.length%todayText.length]}</b><p>사주는 결정을 대신하기보다 서로를 이해하기 위한 참고 도구로 활용해 주세요.</p></div></div></section>{members.length>0&&<section className="section"><div className="section-head"><div><p className="eyebrow">QUICK VIEW</p><h2>가족 한눈에 보기</h2></div><button className="text-btn" onClick={()=>go('family')}>전체 보기 →</button></div><div className="quick-grid">{members.slice(0,4).map(m=>{const p=calc(m.birthDate,m.birthTime);return <button className="quick" key={m.id} onClick={()=>{setSelectedId(m.id);go('family')}}><span className="quick-avatar">{avatar(m.role)}</span><span><b>{m.name}</b><small>{m.role} · {p.day}</small></span><i>→</i></button>})}</div></section>}</>}
 {view==='family'&&<><div className="page-title"><div><p className="eyebrow">MY FAMILY</p><h1>가족 구성원</h1><p>한 사람을 선택하면 사주 원국과 오행을 확인할 수 있습니다.</p></div><button className="primary" onClick={openAdd}>＋ 가족 추가</button></div>{members.length===0?<div className="empty"><div>👨‍👩‍👧‍👦</div><h2>아직 가족이 없어요</h2><p>첫 가족을 등록하고 Family Saju를 시작해 보세요.</p><button className="primary" onClick={openAdd}>가족 등록하기</button></div>:<><div className="members">{members.map(m=><button className={`member ${selected?.id===m.id?'active':''}`} key={m.id} onClick={()=>setSelectedId(m.id)}><span className="avatar">{avatar(m.role)}</span><span><b>{m.name}</b><small>{m.role} · {m.birthDate} {m.birthTime}</small></span><i>→</i></button>)}</div>{selected&&selectedP&&<section className="profile"><div className="profile-head"><div><p className="eyebrow">SAJU PROFILE</p><h2>{avatar(selected.role)} {selected.name}</h2><p>{selected.role} · {selected.gender} · {selected.birthDate} {selected.birthTime}</p></div><div className="profile-actions"><span className="status">계산 완료</span><button onClick={()=>openEdit(selected)}>수정</button><button className="danger" onClick={()=>remove(selected.id)}>삭제</button></div></div><div className="notice"><b>참고 안내</b><span>현재 원국 계산은 브라우저에서 동작하는 간편 계산입니다. 절입 시각·지역시·서머타임 등을 반영하는 전문 만세력과 결과가 다를 수 있습니다.</span></div><div className="saju-grid">{[['년주',selectedP.year],['월주',selectedP.month],['일주',selectedP.day],['시주',selectedP.time]].map(([l,v])=><div key={l}><small>{l}</small><strong>{v}</strong><span>{[...v].map(el).join(' · ')}</span></div>)}</div><div className="element-card"><div><b>오행 분포</b><small>현재 원국의 천간·지지를 단순 집계</small></div><div className="bars">{Object.entries(selectedP.elements).map(([k,v])=><div key={k}><span>{k}</span><i><em style={{width:`${v/8*100}%`}}/></i><b>{v}</b></div>)}</div></div>{ranking.length>0&&<div className="mini-ranking"><div><p className="eyebrow">RELATIONSHIP SNAPSHOT</p><h3>{selected.name}과 가장 잘 맞는 가족</h3></div>{ranking.slice(0,3).map(x=><button key={x.m.id} onClick={()=>{setCompareId(x.m.id);go('relationship')}}><span>{avatar(x.m.role)}</span><b>{x.m.name}</b><strong>{x.r.score}</strong></button>)}</div>}</section>}</>}</>}
 {view==='relationship'&&<><div className="page-title"><div><p className="eyebrow">RELATIONSHIP</p><h1>두 사람의 관계 보기</h1><p>사주를 관계의 정답이 아니라 대화를 시작하는 참고점으로 활용해 보세요.</p></div></div>{members.length<2?<div className="empty"><div>↔</div><h2>두 명 이상 등록해 주세요</h2><p>가족 구성원을 추가하면 관계 분석을 사용할 수 있습니다.</p><button className="primary" onClick={openAdd}>가족 추가하기</button></div>:<><div className="compare-box"><label>기준 가족<select value={meId} onChange={e=>{setMeId(e.target.value);if(e.target.value===compareId)setCompareId('')}}><option value="">선택하세요</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select></label><div className="arrow">↔</div><label>상대 가족<select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">선택하세요</option>{members.filter(m=>m.id!==meId).map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select></label></div>{me&&compare&&<div className="relation-result"><div className={`relation-score ${relation(calc(me.birthDate,me.birthTime),calc(compare.birthDate,compare.birthTime)).tone}`}><strong>{relation(calc(me.birthDate,me.birthTime),calc(compare.birthDate,compare.birthTime)).score}</strong><span>/ 100</span></div><div><p className="eyebrow">{me.name} × {compare.name}</p><h2>{relation(calc(me.birthDate,me.birthTime),calc(compare.birthDate,compare.birthTime)).label}</h2><p>{relation(calc(me.birthDate,me.birthTime),calc(compare.birthDate,compare.birthTime)).text}</p></div></div>}<div className="conversation"><div><p className="eyebrow">CONVERSATION GUIDE</p><h3>지금 어떤 이야기를 해야 하나요?</h3><select value={situation} onChange={e=>setSituation(e.target.value)}><option value="">상황을 선택하세요</option><option>진로</option><option>돈</option><option>부부갈등</option><option>자녀</option><option>부모님</option></select></div><div className="conversation-result"><span>대화 팁</span><b>{guide}</b></div></div></>}</>}</main></div>
 {showForm&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setShowForm(false)}}><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">FAMILY PROFILE</p><h2>{editId?'가족 정보 수정':'가족 구성원 추가'}</h2></div><button type="button" className="close" onClick={()=>setShowForm(false)}>×</button></div><label>이름<input autoFocus value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="예: 민수" required/></label><div className="row"><label>관계<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><label>성별<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>남성</option><option>여성</option><option>선택 안 함</option></select></label></div><div className="row"><label>생년월일<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} required/></label><label>태어난 시각<input type="time" value={form.birthTime} onChange={e=>setForm({...form,birthTime:e.target.value})} required/></label></div><label>메모 <span className="optional">선택</span><input value={form.note||''} onChange={e=>setForm({...form,note:e.target.value})} placeholder="예: 요즘 진로를 고민 중"/></label><button className="primary submit">{editId?'변경사항 저장':'가족 등록하기'}</button></form></div>}</div>}
export default App;
