import { useEffect, useMemo, useRef, useState } from 'react';

type Member = { id:string; name:string; role:string; birthDate:string; birthTime:string; gender:string };
type Pillars = { year:string; month:string; day:string; time:string; elements:Record<string,number> };
const STORAGE_KEY='family-saju-members-v5';
const emptyForm={name:'',role:'아빠',birthDate:'',birthTime:'',gender:'남성'};
const roles=['본인','아빠','엄마','아들','딸','할아버지','할머니','배우자','형제','자매','기타'];
const avatar=(role:string)=>['엄마','할머니','딸','자매'].includes(role)?'👩':['아빠','할아버지','아들','형제','배우자'].includes(role)?'👨':role==='본인'?'🧑':'👤';
const stems=['갑','을','병','정','무','기','경','신','임','계'],branches=['자','축','인','묘','진','사','오','미','신','유','술','해'];
const elementOf=(ch:string)=>({갑:'목',을:'목',인:'목',묘:'목',병:'화',정:'화',사:'화',오:'화',무:'토',기:'토',진:'토',축:'토',술:'토',미:'토',경:'금',신:'금',유:'금',임:'수',계:'수',자:'수',해:'수'} as Record<string,string>)[ch]??'토';
function calcPillars(date:string,time:string):Pillars{const d=new Date(`${date}T${time||'12:00'}:00`);const y=d.getFullYear(),m=d.getMonth()+1,day=d.getDate(),hour=d.getHours();const yearBoundary=m>2||(m===2&&day>=4);const pillarYear=y-(yearBoundary?0:1);const yearIndex=((pillarYear-4)%60+60)%60;const year=stems[yearIndex%10]+branches[yearIndex%12];const termDays=[6,4,6,5,6,6,7,7,8,8,7,7];const branchByMonth=[1,2,3,4,5,6,7,8,9,10,11,0];const monthBranch=(branchByMonth[m-1]-(day<termDays[m-1]?1:0)+12)%12;const monthStem=((yearIndex%10)%5*2+monthBranch)%10;const month=stems[monthStem]+branches[monthBranch];const days=Math.floor(Date.UTC(y,m-1,day)/86400000);const dayIndex=((days+49)%60+60)%60;const dayP=stems[dayIndex%10]+branches[dayIndex%12];const hourBranch=Math.floor(((hour+1)%24)/2);const timeP=stems[(dayIndex%10*2+hourBranch)%10]+branches[hourBranch];const elements={목:0,화:0,토:0,금:0,수:0} as Record<string,number>;[year,month,dayP,timeP].forEach(p=>[...p].forEach(c=>elements[elementOf(c)]++));return{year,month,day:dayP,time:timeP,elements};}
function relationText(a:Pillars,b:Pillars){const score=Math.min(100,55+a.elements.목*b.elements.수*3+a.elements.화*b.elements.목*2+a.elements.토*b.elements.화*2);if(score>=78)return{score,label:'강한 조화',text:'서로의 장점을 살려주기 쉬운 조합입니다. 중요한 대화에서는 상대의 강점을 먼저 인정해 주세요.'};if(score>=65)return{score,label:'좋은 흐름',text:'기본적인 협력이 가능한 조합입니다. 감정이 올라오면 결론보다 서로의 입장을 먼저 확인해 보세요.'};return{score,label:'조율이 필요',text:'차이를 문제로 보기보다 역할과 속도의 차이로 받아들이면 관계가 훨씬 편안해질 수 있습니다.'};}
function App(){
 const[members,setMembers]=useState<Member[]>([]),[selectedId,setSelectedId]=useState<string|null>(null),[showForm,setShowForm]=useState(false),[editingId,setEditingId]=useState<string|null>(null),[form,setForm]=useState(emptyForm),[loaded,setLoaded]=useState(false),[meId,setMeId]=useState<string|null>(null),[compareId,setCompareId]=useState(''),[situation,setSituation]=useState('');const fileRef=useRef<HTMLInputElement>(null);
 useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved){const data=JSON.parse(saved);if(Array.isArray(data.members))setMembers(data.members);if(typeof data.meId==='string')setMeId(data.meId)}}catch{}setLoaded(true)},[]);useEffect(()=>{if(loaded)localStorage.setItem(STORAGE_KEY,JSON.stringify({version:5,members,meId}))},[members,meId,loaded]);
 const selected=useMemo(()=>members.find(m=>m.id===selectedId)??members[0],[members,selectedId]);const compare=members.find(m=>m.id===compareId);const selectedP=selected?calcPillars(selected.birthDate,selected.birthTime):null;const relation=selected&&compare?relationText(calcPillars(selected.birthDate,selected.birthTime),calcPillars(compare.birthDate,compare.birthTime)):null;
 function openAdd(){setEditingId(null);setForm(emptyForm);setShowForm(true)}function openEdit(m:Member){setEditingId(m.id);setForm({...m});setShowForm(true)}function saveMember(e:React.FormEvent){e.preventDefault();if(!form.name.trim()||!form.birthDate||!form.birthTime)return;if(editingId){setMembers(p=>p.map(m=>m.id===editingId?{...m,...form,name:form.name.trim()}:m));setSelectedId(editingId)}else{const member={...form,name:form.name.trim(),id:crypto.randomUUID()};setMembers(p=>[...p,member]);setSelectedId(member.id);if(!meId&&form.role==='본인')setMeId(member.id)}setShowForm(false);setEditingId(null);setForm(emptyForm)}
 function removeMember(id:string){if(!window.confirm('이 가족 구성원을 삭제할까요?'))return;setMembers(p=>p.filter(m=>m.id!==id));if(selectedId===id)setSelectedId(null);if(meId===id)setMeId(null);if(compareId===id)setCompareId('')}
 function exportData(){const blob=new Blob([JSON.stringify({version:5,exportedAt:new Date().toISOString(),members,meId},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='family-saju-backup.json';a.click();URL.revokeObjectURL(url)}
 function importData(e:React.ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(String(reader.result));if(!Array.isArray(data.members))throw new Error('invalid');const clean=data.members.filter((m:Member)=>m&&typeof m.name==='string'&&typeof m.birthDate==='string'&&typeof m.birthTime==='string');if(!clean.length&&data.members.length)throw new Error('invalid');setMembers(clean);setMeId(typeof data.meId==='string'&&clean.some((m:Member)=>m.id===data.meId)?data.meId:null);setSelectedId(clean[0]?.id??null);setCompareId('');alert(`${clean.length}명의 가족 정보를 불러왔습니다.`)}catch{alert('백업 파일을 읽지 못했습니다. Family Saju AI에서 내보낸 JSON 파일인지 확인해 주세요.')}finally{e.target.value=''}};reader.readAsText(file)}
 const situationText=situation==='진로'?'조언보다 선택지를 묻고, 결정권은 상대에게 남겨보세요.':situation==='돈'?'금액과 사실을 먼저 정리한 뒤 감정적인 평가를 분리해 이야기해 보세요.':situation==='부부갈등'?'누가 옳은지보다 지금 원하는 변화 한 가지를 구체적으로 말해보세요.':situation==='자녀'?'결과보다 노력과 과정을 먼저 인정한 뒤 다음 행동을 함께 정해보세요.':situation==='부모님'?'걱정에서 나온 말임을 인정하고, 내가 원하는 도움의 범위를 구체적으로 알려주세요.':'상대의 말을 먼저 한 문장으로 요약한 뒤 내 생각과 원하는 행동을 차분하게 말해보세요.';
 return <div className="app"><header className="topbar"><div className="brand"><span className="brand-mark">☯</span><div><strong>Family Saju AI</strong><small>가족을 이해하는 새로운 방법</small></div></div><div className="top-actions"><button className="data-btn" onClick={exportData} disabled={!members.length}>백업</button><button className="data-btn" onClick={()=>fileRef.current?.click()}>복원</button><input ref={fileRef} type="file" accept="application/json" hidden onChange={importData}/><span className="version">v0.6</span></div></header><div className="workspace"><aside className="sidebar"><div className="sidebar-title"><div><p className="eyebrow">MY BOARD</p><b>내 가족</b></div><button className="add-mini" onClick={openAdd}>＋</button></div><div className="board-item active"><span className="board-icon">☯</span><span><b>우리 가족</b><small>{members.length}명 등록됨</small></span></div><div className="sidebar-label">가족 구성원</div>{members.length===0?<div className="sidebar-empty">아직 등록된 가족이 없습니다.</div>:members.map(m=><button key={m.id} className={`side-member ${selected?.id===m.id?'selected':''}`} onClick={()=>setSelectedId(m.id)}><span>{avatar(m.role)}</span><span><b>{m.name}</b><small>{m.role}{m.id===meId?' · 나':''}</small></span></button>)}<button className="sidebar-add" onClick={openAdd}>＋ 가족 구성원 추가</button></aside>
 <main className="content"><section className="hero"><div><p className="eyebrow">FAMILY RELATIONSHIP</p><h1>사주를 보고,<br/><em>대화의 방법</em>을 찾습니다.</h1><p className="hero-copy">가족의 생년월일시를 바탕으로 전통 간지와 오행의 흐름을 정리하고, 두 사람의 관계를 대화의 관점에서 살펴봅니다.</p></div><div className="hero-card"><span>현재 단계</span><strong>{members.length?'가족 프로필 준비 완료':'가족 정보 등록'}</strong><p>{members.length?'가족을 선택하고 만세력·관계 분석을 확인해 보세요.':'가족의 생년월일과 태어난 시각을 등록해 주세요.'}</p></div></section>
 <section className="section"><div className="section-head"><div><p className="eyebrow">MY FAMILY</p><h2>가족 구성원</h2></div><button className="primary" onClick={openAdd}>＋ 가족 추가</button></div>{members.length===0?<div className="empty"><div className="empty-icon">👨‍👩‍👧‍👦</div><h3>아직 가족이 등록되지 않았어요</h3><p>입력한 가족 정보는 이 브라우저에 저장됩니다. 다른 기기로 옮길 때는 상단의 백업 기능을 사용하세요.</p><button className="primary" onClick={openAdd}>첫 가족 등록하기</button></div>:<div className="members">{members.map(m=><button className={`member ${selected?.id===m.id?'active':''}`} key={m.id} onClick={()=>setSelectedId(m.id)}><span className="avatar">{avatar(m.role)}</span><span><b>{m.name}</b><small>{m.role} · {m.birthDate} {m.birthTime}</small></span></button>)}</div>}</section>
 {selected&&selectedP&&<section className="profile"><div className="profile-head"><div><p className="eyebrow">SAJU PROFILE</p><h2>{avatar(selected.role)} {selected.name}</h2><p>{selected.role} · {selected.gender} · {selected.birthDate} {selected.birthTime}</p></div><div className="profile-actions"><span className="status">계산 완료</span><button onClick={()=>openEdit(selected)}>수정</button><button className="danger" onClick={()=>removeMember(selected.id)}>삭제</button></div></div><div className="notice"><b>사주 원국</b><span>양력 날짜와 입력 시각을 기준으로 간지를 계산합니다. 절입일은 현재 참고용 근사값이며, 지역시각·정밀 절기 계산을 적용하는 전문 만세력과는 결과가 달라질 수 있습니다.</span></div><div className="saju-grid">{[['년주',selectedP.year],['월주',selectedP.month],['일주',selectedP.day],['시주',selectedP.time]].map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong><span>{value.split('').map(elementOf).join(' · ')}</span></div>)}</div><div className="element-row"><b>오행 분포</b>{Object.entries(selectedP.elements).map(([k,v])=><span key={k}>{k} {v}</span>)}</div></section>}
 {members.length>1&&<section className="section compare"><div className="section-head"><div><p className="eyebrow">RELATIONSHIP</p><h2>두 사람의 관계 보기</h2></div></div><div className="compare-box"><label>나 / 기준 가족<select value={meId??''} onChange={e=>{setMeId(e.target.value);if(e.target.value===compareId)setCompareId('')}}><option value="">선택하세요</option>{members.map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select></label><div className="arrow">↔</div><label>상대 가족<select value={compareId} onChange={e=>setCompareId(e.target.value)}><option value="">선택하세요</option>{members.filter(m=>m.id!==meId).map(m=><option key={m.id} value={m.id}>{m.name} · {m.role}</option>)}</select></label></div>{meId&&compare&&relation?<div className="relationship-ready"><div className="score"><strong>{relation.score}</strong><span>/ 100</span></div><div><b>{members.find(m=>m.id===meId)?.name} × {compare.name} · {relation.label}</b><span>{relation.text}</span></div></div>:<div className="relationship-empty">두 사람을 선택하면 관계 흐름과 대화 팁이 표시됩니다.</div>}<div className="conversation"><div><p className="eyebrow">CONVERSATION GUIDE</p><b>지금 어떤 이야기를 해야 하나요?</b><select value={situation} onChange={e=>setSituation(e.target.value)}><option value="">상황을 선택하세요</option><option>진로</option><option>돈</option><option>부부갈등</option><option>자녀</option><option>부모님</option></select></div>{situation&&<div className="conversation-result"><strong>대화 팁</strong><span>{situationText}</span></div>}</div></section>}
 <section className="section guide"><p className="eyebrow">AI CONVERSATION</p><h2>사주는 관계를 단정하지 않습니다.</h2><p>생년월일 정보는 대화를 시작하기 위한 참고 자료입니다. 실제 관계에서는 서로의 경험과 현재 상황을 우선해 주세요.</p><div className="guide-cards"><div><b>① 상황</b><span>무슨 일이 있었는지 구체적으로 말합니다.</span></div><div><b>② 인정</b><span>상대가 중요하게 생각하는 지점을 먼저 확인합니다.</span></div><div><b>③ 요청</b><span>비난 대신 내가 원하는 행동을 한 가지로 요청합니다.</span></div></div></section></main></div>
 {showForm&&<div className="modal-backdrop" onMouseDown={()=>setShowForm(false)}><form className="modal" onSubmit={saveMember} onMouseDown={e=>e.stopPropagation()}><div className="modal-head"><div><p className="eyebrow">{editingId?'EDIT MEMBER':'NEW MEMBER'}</p><h2>{editingId?'가족 정보 수정':'가족 등록'}</h2></div><button type="button" className="close" onClick={()=>setShowForm(false)}>×</button></div><label>이름<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="예: 홍길동" required/></label><label>가족 관계<select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}>{roles.map(r=><option key={r}>{r}</option>)}</select></label><div className="row"><label>생년월일<input type="date" value={form.birthDate} onChange={e=>setForm({...form,birthDate:e.target.value})} required/></label><label>태어난 시각<input type="time" value={form.birthTime} onChange={e=>setForm({...form,birthTime:e.target.value})} required/></label></div><label>성별<select value={form.gender} onChange={e=>setForm({...form,gender:e.target.value})}><option>남성</option><option>여성</option></select></label><button className="primary submit">{editingId?'저장하기':'등록하기'}</button></form></div>}</div>;
}
export default App;
